### PR TITLE
Add the ability to find matching NoteOff event

### PR DESCRIPTION
**Pull request by tleyden**
Fixes https://github.com/vishnubob/python-midi/issues/58

### CODE REVIEW

**Comment by tleyden** [comment]
Found a nasty bug, closing this PR until its fixed

**Comment by tleyden** [comment]
Nevermind, the bug was in [higher level code](https://github.com/tleyden/climate-music/commit/ca12ffae5ea0bb7c94e8077976c07db687a370dc).

**Comment by tleyden** [comment]
Found another issue as [described here](https://github.com/tleyden/climate-music/issues/1)

I updated the unit test to detect this issue, but I'm not sure what a fix is.

Changing [this line](https://github.com/tleyden/python-midi/commit/7e82d99595fe8fba9f98cb9b532a9ec846bc162e#diff-a3ee8ed9ecce93718fad630ad21f9376R78) from

```
        # If it's before the tick of the NoteOn event, ignore it
        if event.tick < noteOnEvent.tick:
            continue
```

to

```
        # If it's before the tick of the NoteOn event, ignore it
        if event.tick <= noteOnEvent.tick:
            continue
```

will fix the issue, but then it would miss things like:

```
   midi.NoteOnEvent(tick=260, channel=0, data=[38, 10]),
   midi.NoteOffEvent(tick=260, channel=0, data=[38, 10]),
```

which I believe is valid MIDI.

I guess the real fix is to take into account *ordering* .. @tdhsmith is there an index associated with each event that can be used so that when finding a NoteOffEvent, it would only look at things that have a greater event index?

**Comment by tdhsmith** [comment]
I had assumed the order of events within a track should always be the correct order of execution, but I guess I don't know what the specification says.  I do know Standard MIDI Files don't store any kind of index other than the tick and their file-internal order. 

If you want a quick way to keep track of the file-internal order, you could definitely use python's `enumerate` on the `Track` to generate indices for all the events. (or switch to an index-based for loop, but that doesn't feel as "python-y" to me :stuck_out_tongue:)

```
midi.NoteOffEvent(tick=14280, channel=0, data=[68, 64]),
midi.NoteOnEvent(tick=14280, channel=0, data=[68, 126]),
```

(This is from your linked issue.) Are there other notes involved here on pitch 68? I agree zero-length notes should be valid, but I think the Off should always occur after the On, so this doesn't seem right.

**Comment by tleyden** [comment]
> but I think the Off should always occur after the On, so this doesn't seem right.

Yep, agreed.  I think I may have copied-pasted the wrong snippet there.  I'll dig into it.

**Comment by vishnubob** [comment]
Hi folks, just got back from vacation, and will be reviewing all the recent issues, patches, etc.  With respect to ordering, it's important to understand that events in a MIDI track stored in a MIDI file are stored in order with a relative tick.  This guarantees the order of the events is always "correct".  MIDI makes no assumptions about pairing of events (such as a NoteOn followed by a NoteOff).  For example, a glissando might be composed of many subsequent NoteOn events followed by a single NoteOff event.  If two MIDI events are stored with a tick delta of zero, they will be enqueued exactly in the order they were stored and transmitted in that order.  They rate of transmission will be dictated by the hardware speed of the MIDI bus, the OS, etc.  I'm not sure what to think about this patch.  On the one hand, it's a nice convenience for MIDI files that have neatly paired NoteOn/NoteOff events, but (as I said earlier), nothing about MIDI guarantees this, making it only applicable for some subset of tracks.  My thinking is to add this to a new module of "contributed code", which will be a nice place holder for algorithms that are specific to flavors of MIDI tracks, but not part of the library proper.  I need some more time to consider the best approach, and will follow up later this week.

**Comment by tleyden** [comment]
@vishnubob based on your comments, if this only works for a subset of midi tracks then I don't think this patch should be merged.

I have some follow up questions.

> For example, a glissando might be composed of many subsequent NoteOn events followed by a single NoteOff event.

I'd be curious to see what that looked like in terms of `midi.NoteOffEvent` and `midi.NoteOnEvent`

> MIDI makes no assumptions about pairing of events (such as a NoteOn followed by a NoteOff).

Got it, so it's a faulty assumption to assume that there is a corresponding NoteOff for every NoteOn event.

Taking a big step back, do you think it's possible to write a general purpose algorithm that could satisfy [these requirements](https://github.com/vishnubob/python-midi/issues/56#issue-91959752) but work for any midi track?  Or would a whole new level of abstraction be required as mentioned [here](https://github.com/vishnubob/python-midi/issues/56#issuecomment-117281849)?

> Of course the whole thing would probably be better handled by a library that handles notes from a musical standpoint, but that introduces a lot of complexity and this project seems to aim for reproducing MIDI and not a whole musical notation system.

**Pull request closed without merging**
